name: "\U0001F41B Bug report"
description: "Complete the following issue to report a bug."
title: "[Bug]: "
labels: ["Bug", "Triage"]
assignees: [""]
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out this bug report!"
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug:"
      description: "A clear and concise description of what the bug is."
      placeholder: ""
      value: ""
    validations:
      required: true
- type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce the behavior:"
      description: "."
      placeholder: ""
      value: "1. Go to ..., 2. Click on ..., 3. Scroll down to ..., 4. See error ..."
    validations:
      required: true
- type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior:"
      description: "A clear and concise description of what you expected to happen."
      placeholder: ""
      value: ""
- type: textarea
    id: possible_solution
    attributes:
      label: "Possible solution:"
      description: "Not obligatory, but suggest a fix/reason for the bug."
      placeholder: ""
      value: ""
