name: "\U0001F41B Bug report"
description: "Complete the following issue to report a bug."
title: "[Bug]: "
labels: ["Bug", "Triage"]
assignees: [""]
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out this bug report!"
  - type: input
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: ""
      value: ""
    validations:
      required: true
