name: "\U0001F41B Bug report"
description: "Complete the following issue to report a bug."
title: "[Bug]: "
labels: ["Bug", "Triage"]
assignees: [""]
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out this bug report!"
