name: "\U0001F41B Bug report"
description: "Complete the following issue to report a bug."
title: "[Bug]: "
labels: ["Bug", "Triage"]
assignees: [""]
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out this bug report!"
  - type: input
    id: description
    attributes:
      label: "Describe the bug:"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce the behavior:"
      description: "List of steps to reproduce the behavior."
      placeholder: "1. Go to ..., 2. Click on ..., 3. Scroll down to ..., 4. See error ..."
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior:"
      description: "A clear and concise description of what you expected to happen."
  - type: textarea
    id: possible_solution
    attributes:
      label: "Possible solution:"
      description: "Not obligatory, but suggest a fix/reason for the bug."
  - type: input
    id: logs
    attributes:
      label: "Relevant logs:"
      description: "If applicable, add logs to help identify the root cause of your problem."
  - type: input
    id: screenshots
    attributes:
      label: "Relevant screenshots:"
      description: "If applicable, add screenshots to help explain your problem."
